name: Update README with Latest Solutions

on:
    push:
        branches:
            - main
        paths:
            - "LeetCode Daily/**"
            - "Weekly Contest/**"

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 10 # Fetch more commits to find actual solution changes

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Update README with latest solutions
              run: |
                  echo "🚀 Fast processing of LeetCode solutions and README update..."
                  python update_readme_fast.py

            - name: Check for changes
              id: check_changes
              run: |
                  if git diff --quiet README.md latest_solutions.json latest_solutions_section.txt; then
                      echo "changes=false" >> $GITHUB_OUTPUT
                      echo "✅ No changes detected"
                  else
                      echo "changes=true" >> $GITHUB_OUTPUT
                      echo "📋 Changes detected in README or solution files"
                  fi

            - name: Commit and push changes
              if: steps.check_changes.outputs.changes == 'true'
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add README.md latest_solutions.json latest_solutions_section.txt
                  git commit -m "📝 Update README with latest LeetCode solutions

                  Auto-generated update including:
                  - Latest solution entries
                  - Updated language statistics
                  - Refreshed solution links"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Summary
              run: |
                  if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
                      echo "🎉 README successfully updated with latest solutions!"
                  else
                      echo "ℹ️ No updates needed - README is already current"
                  fi
