name: Update README

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 0 * * *" 

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Ruby dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y ruby ruby-dev
                  sudo gem install github-linguist

            - name: Install Python dependencies in a virtual environment
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install --upgrade pip
                  pip install pygments

            - name: Calculate language stats and update README
              run: |
                  source venv/bin/activate
                  python calculate_stats.py

            - name: Commit changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add README.md
                  git commit -m 'Update README with language stats'
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
